### ISSUE TITLE
Error when running code

### ISSUE THREAD

**Issue by luxiaohua-26** [come880412/CTGAN#4]
root@autodl-container-b2e2118052-bec5573d:~/autodl-tmp/CTGAN-main# python train.py
Namespace(aux_loss=False, batch_size=4, cloud_model_path='/root/autodl-tmp/CTGAN-main/data/Sen2_MTC/Pretrain/Feature_Extrator_FS2.pth', dataset_name='Sen2_MTC', gan_mode='lsgan', gpu_id='0', image_size=256, in_channel=4, label_noise=False, lambda_L1=100.0, lambda_aux=50.0, load_dis='', load_gen='', lr=0.0002, manual_seed=2022, n_epochs=100, optimizer='AdamW', out_channel=4, predict_image_path='./image_out', root='/root/autodl-tmp/CTGAN-main/data/Sen2_MTC/dataset', save_model_path='./checkpoints', workers=0)
Load cloud_detection_model
Load CTGAN model
Start training!
Train[0/100]:   0% 0/595 [00:00<?, ? step/s]
learning rate = 0.0002000
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    train(opt, GEN, DIS, cloud_detection_model, optimizer_G, optimizer_D, train_loader, val_loader)
  File "train.py", line 71, in train
    fake_B, cloud_mask, aux_pred = model_GEN(real_A)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/CTGAN-main/model/CTGAN.py", line 65, in forward
    att0, out0, pred_0 = self.feature_extractor(x0)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/CTGAN-main/model/FE.py", line 106, in forward
    out = self.ASPP(out)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/CTGAN-main/model/FE.py", line 48, in forward
    res.append(conv(x))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/CTGAN-main/model/model_component.py", line 35, in forward
    x = super(ASPPPooling, self).forward(x)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/instancenorm.py", line 57, in forward
    return F.instance_norm(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 2326, in instance_norm
    _verify_spatial_size(input.size())
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 2293, in _verify_spatial_size
    raise ValueError("Expected more than 1 spatial element when training, got input size {}".format(size))
ValueError: Expected more than 1 spatial element when training, got input size torch.Size([4, 128, 1, 1])

**Comment by come880412** [comment]
Hi, I apologize for the delayed response. 
Have you checked the shape of your input data?
